judgeConfig:
  structure:
    filename: 'xxxxxxxxxx-xxx-操作系统第二次作业'
    l1_title: '操作系统第二次作业'
    l2_titles:
      - 1.实验内容
      - 2.实验思路
      - 3.实验源码
      - 4.实验结果
      - 5.实验总结与反思
  limitations:
    - min_len: 10
      max_len: 999
    - min_len: 10
    - min_len: 200
    - min_len: 10
    - min_len: 10
  scores:
    - score: 0.5
      desc: 实验内容
    - score: 1
      desc: 实验思路
    - score: 4
      desc: 实验源码
      check_points:
        - create
        - destroy
        - activate
        - request
        - release
    - score: 3
      desc: 实验结果
      check_points:
        - 200000
        - 200000
        - 200000
        - 200000
        - 200000
    - score: 1
      desc: 实验总结与反思
    - score: 0.5
      desc: 文件结构和名称
  total_score: 10
